site_name: 许你一世凡尘的博客
site_author: healwy

copyright: Copyright &copy; 2022 Healwy
nav:
  - 主页: index.md
  - 小工具: 
    - Linux:
      - 命令: 
        - 网络: tools/linux/cmd/network.md
  - 问题:
    - Linux:
      - Ubuntu 18.04 卸载python3后进不去图形界面解决方法: problem/linux/problem1.md
  - 关于: 
    - 关于: about/about.md

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: blue
  language:
    zh
  logo: assets/logo.png  
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.top
    - navigation.expand
    - navigation.indexes
    - toc.follow
  font: false
  # font:
  #   code: Roboto Mono

extra:
  generator: false  
  
markdown_extensions:
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

